# Generated by Django 5.2 on 2025-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlucoseLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=255)),
                ("serial_number", models.UUIDField(editable=False)),
                ("device_timestamp", models.DateTimeField()),
                ("record_type", models.IntegerField()),
                ("glucose_value_trend", models.IntegerField(db_comment="mg/dL")),
                (
                    "glucose_scan",
                    models.IntegerField(blank=True, db_comment="mg/dL", null=True),
                ),
                (
                    "nonnumeric_rapid_acting_insulin",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "rapid_acting_insulin",
                    models.IntegerField(blank=True, db_comment="units", null=True),
                ),
                ("nonnumeric_food_data", models.CharField(blank=True, null=True)),
                (
                    "carbohydrates",
                    models.IntegerField(blank=True, db_comment="grams", null=True),
                ),
                ("carbohydrate_servings", models.IntegerField(blank=True, null=True)),
                (
                    "nonnumeric_slow_release_insulin",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "slow_release_insulin",
                    models.IntegerField(blank=True, db_comment="units", null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "glucose_test_strip",
                    models.IntegerField(blank=True, db_comment="mg/dL ", null=True),
                ),
                (
                    "ketone",
                    models.IntegerField(blank=True, db_comment="mmol/L", null=True),
                ),
                (
                    "mealtime_insulin",
                    models.IntegerField(blank=True, db_comment="units", null=True),
                ),
                (
                    "correction_insulin",
                    models.IntegerField(blank=True, db_comment="units", null=True),
                ),
                (
                    "user_changed_insulin",
                    models.IntegerField(blank=True, db_comment="units", null=True),
                ),
            ],
        ),
    ]
